"""FastAPI backend for SomaliFish AI.

STEP 5. Serves the precomputed daily prediction files and the web map.
No database: predictions are small static JSON, regenerated by predict.py.

Usage:
    python src/api.py                 # http://127.0.0.1:8000
    python src/api.py --port 8080 --host 0.0.0.0

Endpoints:
    GET /                     the web map
    GET /api/today            newest prediction (falls back to demo data)
    GET /api/day/{date}       a specific day, YYYY-MM-DD
    GET /api/days             which days are available
    GET /api/safety           just the safety summary (small, for slow links)
    GET /api/zone/{lat}/{lon} conditions for the cell containing a point
    GET /api/health           service + data status
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

import config
import safety

WEB_DIR = config.ROOT / "web"

app = FastAPI(title="SomaliFish AI",
              description="Potential fishing zones and sea safety for Somali waters",
              version="0.1.0")

# The payload is ~400 KB of repetitive JSON and the target user is on a slow
# mobile connection; gzip takes it to roughly a sixth of that.
app.add_middleware(GZipMiddleware, minimum_size=1000)


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def latest_payload() -> tuple[dict, str]:
    """Newest prediction, falling back to the bundled demo day.

    The fallback exists because the hackathon demo must not depend on a live
    network. It is always labelled as a fallback so nobody mistakes cached
    data for today's sea state.
    """
    live = config.PREDICTIONS_DIR / "latest.json"
    if live.exists():
        return _load(live), "live"
    demo = config.DEMO_DIR / "latest.json"
    if demo.exists():
        payload = _load(demo)
        payload["stale"] = True
        return payload, "demo"
    raise HTTPException(503, "No predictions available. Run src/predict.py")


@app.get("/api/health")
def health() -> dict:
    days = sorted(p.stem for p in config.PREDICTIONS_DIR.glob("20*.json"))
    model = config.MODELS_DIR / "hotspot_xgb.json"
    meta_path = model.with_suffix(".meta.json")
    meta = json.loads(meta_path.read_text()) if meta_path.exists() else {}
    # A model file on disk is not a usable model. Report whether it passed
    # validation, so nothing downstream reads "trained" as "trustworthy".
    validated = bool(meta.get("beats_baselines"))
    return {
        "status": "ok",
        "days_available": len(days),
        "newest_day": days[-1] if days else None,
        "model_file_exists": model.exists(),
        "model_validated": validated,
        "ranking_source": "model" if validated else "physics_index",
        "demo_fallback": (config.DEMO_DIR / "latest.json").exists(),
    }


@app.get("/api/days")
def days() -> dict:
    found = sorted(p.stem for p in config.PREDICTIONS_DIR.glob("20*.json"))
    return {"days": found, "count": len(found)}


@app.get("/api/today")
def today() -> JSONResponse:
    payload, source = latest_payload()
    payload["source"] = source
    return JSONResponse(payload)


@app.get("/api/day/{date}")
def day(date: str) -> JSONResponse:
    path = config.PREDICTIONS_DIR / f"{date}.json"
    if not path.exists():
        raise HTTPException(404, f"No prediction for {date}")
    return JSONResponse(_load(path))


@app.get("/api/safety")
def safety_summary() -> dict:
    """Just the headline banner - a few hundred bytes, for slow connections."""
    payload, source = latest_payload()
    return {
        "date": payload["date"],
        "source": source,
        "safety": payload["safety"],
        "thresholds": payload["thresholds"],
        "labels": safety.LABELS,
    }


@app.get("/api/zone/{lat}/{lon}")
def zone(lat: float, lon: float) -> dict:
    """Conditions for the grid cell containing a point."""
    payload, source = latest_payload()
    cells = payload["cells"]
    best_i, best_d = None, 1e9
    for i, (clat, clon) in enumerate(zip(cells["lat"], cells["lon"])):
        d = abs(clat - lat) + abs(clon - lon)
        if d < best_d:
            best_i, best_d = i, d
    if best_i is None or best_d > config.GRID_RES * 2:
        raise HTTPException(404, "No ocean cell near that point")

    status = cells["safety"][best_i]
    out = {
        "date": payload["date"],
        "source": source,
        "lat": cells["lat"][best_i],
        "lon": cells["lon"][best_i],
        "safety": {"status": status,
                   "label": safety.LABELS.get(status),
                   "advice": safety.ADVICE.get(status)},
        "conditions": {k: cells[k][best_i] for k in
                       ("sst", "chl", "sst_gradient", "current_speed",
                        "wave_height_max", "wind_speed_max")
                       if cells.get(k) is not None},
        "model": payload.get("model", {}),
    }
    if cells.get("score") is not None:
        out["fishing_potential"] = cells["score"][best_i]
    return out


@app.get("/")
def index() -> FileResponse:
    page = WEB_DIR / "index.html"
    if not page.exists():
        raise HTTPException(404, "web/index.html not found")
    return FileResponse(page)


if WEB_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(WEB_DIR)), name="static")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--reload", action="store_true")
    args = parser.parse_args()

    import uvicorn
    print(f"SomaliFish AI -> http://{args.host}:{args.port}")
    uvicorn.run("api:app" if args.reload else app,
                host=args.host, port=args.port, reload=args.reload)


if __name__ == "__main__":
    main()
